apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-a
  namespace: default
spec:
  replicas: 7
  selector:
    matchLabels:
      app: deployment-a
  template:
    metadata:
      labels:
        app: deployment-a
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "128m"
            memory: "128Mi"
          limits:
            cpu: "256m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
  namespace: default
spec:
  replicas: 7
  selector:
    matchLabels:
      app: deployment-b
  template:
    metadata:
      labels:
        app: deployment-b
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fixed
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fixed-app
  template:
    metadata:
      labels:
        app: fixed-app
      annotations:
        "podtetris/fixed": "true" 
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "123m"
            memory: "123Mi"
          limits:
            cpu: "246m"
            memory: "246Mi"
--- # ReplicaSets
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-a
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs-a
  template:
    metadata:
      labels:
        app: rs-a
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "64m"
            memory: "64Mi"
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-b
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs-b
  template:
    metadata:
      labels:
        app: rs-b
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "256m"
            memory: "256Mi"
--- # StatefulSet stuff
apiVersion: v1
kind: Service
metadata:
  name: statefulset-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "statefulset-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 1024Mi
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi