apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtetris-storage-reader
rules:
  - apiGroups: ["", "storage.k8s.io"]
    resources: 
          - "persistentvolumeclaims"
          - "persistentvolumes"
          - "csinodes"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podtetris-storage-reader-binding
subjects:
  - kind: ServiceAccount
    name: podtetris-sa
    namespace: podtetris
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: podtetris-storage-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtetris-podmoves-writer
rules:
  - apiGroups: ["podtetris.io.podtetris.io"]
    resources: ["podmoves"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podtetris-podmoves-writer-binding
subjects:
  - kind: ServiceAccount
    name: podtetris-sa
    namespace: podtetris
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: podtetris-podmoves-writer
