apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 2 # One per zone?
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      annotations:
        podtetris/fixed: "no"
        podtetris/moveCost: "75"
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"