apiVersion: v1
kind: Pod
metadata:
  name: pod-to-test-the-default-scheduler
spec:
  # No schedulerName specified
  schedulerName: default-scheduler
  containers:
  - name: nginx
    image: nginx:stable-alpine