apiVersion: reply.com/v1alpha1
kind: PodMigration
metadata:
  name: podmigration1
  namespace: default
spec:
  ownerRef:
    apiVersion: "apps/v1"
    kind: "StatefulSet"
    name: "statefulset"
    namespace: "default"
    uid: "972a1b24-e93a-4d3e-8092-1658c2c5e4ac"
  podRef:
    name: "statefulset-0"
    namespace: "default"
    uid: "56dd2b4b-1ffd-4734-917c-3333685bcb6d"
  sourceNode: "kind-worker4"
  targetNode: "kind-worker2"