candidateNodesNumbers:
  random: 3
  byCPU: 2
  byMemory: 2
emptyNodesScoreWeight: 400
costScoreWeight: 1
autoConsolidationScoreThreshold: 0
candidateNodesSelectionMaxRetries: 15
enabledPermutationStrategies:
  - cpu_desc
  - memory_desc
  - random
# randomPermutationCount is the number of random permutations generated
randomPermutationCount: 1
parallelism: 8
dryRun: false
