apiVersion: v1
items:
- apiVersion: podtetris.io.podtetris.io/v1
  kind: ConsolidationPlan
  metadata:
    creationTimestamp: "2026-10-08T10:37:03Z"
    generateName: consolidationplan-
    generation: 1
    name: consolidationplan-spbkp
    namespace: podtetris
    resourceVersion: "1858"
    uid: 00925d0f-cd9d-49e2-b919-ecdc16d0cb72
  spec:
    cost: 700
    freedNodes: 3
    moveCount: 19
    nodesToFree:
    - kind-worker2
    - kind-worker3
    - kind-worker6
    permutationStrategy: random
    score: 500
kind: List
metadata:
  resourceVersion: ""
