apiVersion: podtetris.io.podtetris.io/v1
kind: ConsolidationPlan
metadata:
  labels:
    app.kubernetes.io/name: evictor
    app.kubernetes.io/managed-by: kustomize
  name: consolidationplan-sample
spec:
  freedNodes: 2
  nodesToFree:
    - worker-a
    - worker-b
  cost: 10
  score: 90
  moveCount: 3
