apiVersion: podtetris.io.podtetris.io/v1
kind: PodMove
metadata:
  labels:
    app.kubernetes.io/name: evictor
    app.kubernetes.io/managed-by: kustomize
  name: podmove-sample
spec:
  # TODO(user): Add fields here
