apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: podtetris-webhook
webhooks:
  - name: podtetris-webhook.podtetris.svc
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    failurePolicy: Ignore # Ignore, not Fail: if the webhook is down, pod creation should not be blocked cluster-wide.
    timeoutSeconds: 5
    clientConfig:
      service:
        name: podtetris-webhook
        namespace: podtetris
        path: /mutate
        port: 443
      # Replace with the output of gen-certs.sh (base64 tls.crt)
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lKQU5rbTh1ZjQ5QlllTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ294S0RBbUJnTlYKQkFNTUgzQnZaSFJsZEhKcGN5MTNaV0pvYjI5ckxuQnZaSFJsZEhKcGN5NXpkbU13SGhjTk1qWXdOekUyTVRNMQpNakU0V2hjTk16WXdOekV6TVRNMU1qRTRXakFxTVNnd0pnWURWUVFEREI5d2IyUjBaWFJ5YVhNdGQyVmlhRzl2CmF5NXdiMlIwWlhSeWFYTXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKem9lVm8yNm5oNkc4Sm04Y0NCWlJMeE5FNkZ0VW04NWVUUnA4UGVZQ2tXOHdKQVlONGdrSm9OdkVmTFJrMllKawovN1ppb1VxK3hRbkEyWDRoZWdoZ1BRQnRlR3NGdWJBVlo2MnJZVHk2Q2xDdXU1TXZrZUF4QmJadWpZckZBcHZOCngvWnZ1akdQQ3hHMXpCNm9mb0xUNnRnRTZMeGh4U2tvUXNFaGVscUFxVUorZkVjVlNyUmR0ZWNUSUo2a1BaajMKV1V0NDFiZFd6dG5ldGpOS3hqZnlFVTNYMDdsYVZvVlg5NUtrdGhKVjhsZDRnbjlycUZQODFoR1dPQzhHbkorcQowcXJ0dTM0TGxSN2xVUStoUHJqWnRSZmVqbW1VM0FmcVM1aUZBT0tjZjlOc2N4N2RRQkJOTXdXKzRER2dRY1JhCmhpVG5KRWM4MHdEZEVnemhrU3JQN3dJREFRQUJvMTB3V3pCWkJnTlZIUkVFVWpCUWdoOXdiMlIwWlhSeWFYTXQKZDJWaWFHOXZheTV3YjJSMFpYUnlhWE11YzNaamdpMXdiMlIwWlhSeWFYTXRkMlZpYUc5dmF5NXdiMlIwWlhSeQphWE11YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUl6d1A3Y2tBSW15CmpvMVlvbkZ3UHhEU0ovNll4RWloMTlJUXJHL2tlZW43cE1UZ3dHYmdCM2xZblpSVVdNa1FHVHhFVkNjVzJ5V2UKK3hLbXNvUG9YcjFwRWF5YUJLMjRWem5KU0ZHVlVQWHVHMmV2ajJ6anJOcE04UWdJNFF5THNvdmgvRjRlYWZGLwpwUXpjVUxkN1V4Mm9iVDl5ck5rQzgwa0JPSEhBemM1UE14bmxaYWZVQTJIeVg1SjBrWGN0OEt0VExYZDdWbWlrCm9iZm9zVTR6ajRqeDdXNisxRkRHdjJqRm1HYzl6OWpzWjJidDFGWE9IRlJmd3U2MnpKQS9RUk56bjE3ckxTam4Kc2Y5WWppRjlNOHhRQnpib2tkVUp4M2JFTHYwR1dEV0syaWZud2JFbDRJa2NNdlpOaFdtZnc5SU5tUFFsK1I0KwpEYmtXcEI0ZDNPRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - podtetris
