apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podtetris.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "podtetris.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.planner.config) . | nindent 4 }}
