{{- if .Values.planner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podtetris.fullname" . }}-planner-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podtetris.labels" . | nindent 4 }}
data:
  rules.yaml: |
    {{- tpl (toYaml .Values.planner.rules) . | nindent 4 }}
{{- end }}
