{{- if .Values.planner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podtetris.fullname" . }}-scheduler-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podtetris.labels" . | nindent 4 }}
data:
  podtetris-scheduler-config.yaml: |
    {{- toYaml .Values.planner.schedulerConfig | nindent 4 }}
{{- end }}
