apiVersion: v1
kind: Service
metadata:
  name: {{ include "podtetris.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "podtetris.fullname" . }}-webhook
  ports:
    - port: 443
      targetPort: 8443