apiVersion: v1
kind: Pod
metadata:
  name: simulated-burst-pod-xyz
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"