apiVersion: v1
kind: Namespace
metadata:
  name: podtetris
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: podtetris-config
  namespace: podtetris
data:
  config.yaml: |
    randomCandidateNodesNumber: 3
    byCPUCandidateNodesNumber: 2
    podMoveDefaultCost: 10
    emptyNodesScoreWeight: 100
    costScoreWeight: 100
    autoConsolidationScoreThreshold: 12345
    candidateNodesSelectionMaxRetries: 15
    fixedPodAnnotation: "podtetris/fixed"
    podMoveCostAnnotation: "podtetris/moveCost"
    enabledPermutationStrategies:
      - cpu_desc
      - memory_desc
      - random
    parallelism: 8